GUI/Controllers/StructureGeneratorController.cs
using GUI.Helpers;
using GUI.Models;
using Model;
using Shared;
using System;
using System.Collections.Generic;
using System.Drawing.Imaging;
using System.IO;
using System.Net.Mime;
using System.Web;
using System.Web.Mvc;

namespace GUI.Controllers
{
    public class StructureGeneratorController : Controller
    {
        private const string dbFile = "database.xml";

        /// <summary>
        /// Structure generater site
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            InitiateViewBag();
            var model = new StructureGeneratorModel();
            return View(model);
        }

        [HttpGet]
        public ActionResult Get(string id)
        {
            try
            {
                InitiateViewBag();
                var path = Server.MapPath("~/App_Data/");
                var dbReader = new DatabaseReader();
                var model = dbReader.Get(path, id);
                return View("Index", model);
            }
            catch (Exception e)
            {
                return RedirectToAction("Index");
            }
        }

        /// <summary>
        /// Generates structure
        /// </summary>
        /// <param name="model">Structure model</param>
        /// <returns>Json object with image structure or error information</returns>
        [HttpPost]
        public ActionResult Generate(StructureGeneratorModel model)
        {
            try
            {
                var helper = new GeneratorHelper();
                //var path = helper.GeneratePdfStructure(model);
                //var bytes = System.IO.File.ReadAllBytes(path);
                //var base64 = Convert.ToBase64String(bytes);
                var bmp = helper.GenerateImageStructure(model);
                var dbReader = new DatabaseReader();
                if (bmp != null)
                {

                    string base64String = ImageConverters.BitmapToBase64String(bmp);
                    return Json(new { value = base64String, isError = false });
                }
                else
                {
                    throw new Exception(ErrorType.Unknown.ToFriendlyString());
                }
            }
            catch (Exception e)
            {
                return Json(new { isError = true, Error = e.Message });
            }
        }
        /// <summary>
        /// Downloads structure to local user divice
        /// </summary>
        /// <param name="model">Structure model</param>
        /// <returns>File</returns>
        [HttpPost]
        public FileResult Download(StructureGeneratorModel model)
        {
            var helper = new GeneratorHelper();
            //var bmp = helper.GenerateStructure(model);
            var bmp = helper.GenerateImageStructure(model);
            var type = "image/png";
            var imgType = ImageFormat.Png;
            switch (model.DownloadFormat)
            {
                case DownloadType.PDF:
                    type = MediaTypeNames.Application.Pdf;
                    return File(helper.GeneratePdfStructure(model), type, "structure");
                //return File(ImageConverters.ImageToPdf(bmp), type, "structure");
                case DownloadType.JPG:
                    type = MediaTypeNames.Image.Jpeg;
                    imgType = ImageFormat.Jpeg;
                    break;
            }
            var img = ImageConverters.BitmapToByteArray(bmp, imgType);
            return File(img, type, "structure");
        }
        [HttpPost]
        public ActionResult GenerateLink(StructureGeneratorModel model)
        {
            try
            {
                var dbReader = new DatabaseReader();
                var path = Server.MapPath("~/App_Data/");
                string fullPath = Path.Combine(path, dbFile);
                var id = dbReader.Insert(path, model);

                return Json(new { isError = false, Id = id });
            }
            catch (Exception e)
            {
                return Json(new { isError = true, Error = e.Message });
            }
        }

        /// <summary>
        /// Uploads images files
        /// </summary>
        /// <returns>Images list model and rendered html view with image rows</returns>
        [HttpPost]
        public ActionResult UploadImageRow()
        {
            try
            {
                List<PictureUploadModel> images = new List<PictureUploadModel>(); ;

                for (var i = 0; i < Request.Files.Count; ++i)
                {
                    HttpPostedFileBase image = Request.Files[i];
                    var name = image.FileName;
                    name = name.Substring(0, name.LastIndexOf('.'));
                    var fileName = Path.GetFileName(image.FileName);
                    var bytesString = ImageConverters.FileToBase64String(image.InputStream);
                    //if (bytesString != null)
                    images.Add(new PictureUploadModel(name, image.FileName, bytesString));
                }

                string html = PartialView("~/Views/StructureGenerator/EditorTemplates/UploadRows.cshtml", images).RenderToString();
                return Json(new { Model = images, Html = html });
            }
            catch (Exception e)
            {
                return PartialView("~/Views/StructureGenerator/EditorTemplates/UploadRow.cshtml", new PictureUploadModel());
            }

        }
        #region ViewBag
        /// <summary>
        /// Initiates view bag
        /// </summary>
        private void InitiateViewBag()
        {
            ViewBag.Title = "Structure Generator";
            List<SelectListItem> liFonts = new List<SelectListItem>()
            {
                new SelectListItem{Value="Arial", Text = "Arial"},
                new SelectListItem{Value="Brush Script Std", Text = "Brush Script Std"},
                new SelectListItem{Value="Calibri", Text = "Calibri"},
                new SelectListItem{Value="Comic Sans MS", Text="Comic Sans MS"},
                new SelectListItem{Value="Liberation Serif", Text="Liberation Serif"},
                new SelectListItem{Value="Tahoma", Text = "Tahoma"},
                new SelectListItem{Value="Times New Roman", Text = "Times New Roman"},
                new SelectListItem{Value="Verdana", Text = "Verdana"},
            };
            ViewData["FontList"] = liFonts;

            List<SelectListItem> liColors = new List<SelectListItem>()
            {
                new SelectListItem{Value="Black", Text = "Czarny"},
                new SelectListItem{Value="Red", Text = "Czerwony"},
                new SelectListItem{Value="Blue", Text = "Niebieski"},
                new SelectListItem{Value="Green", Text = "Zielony"},
                new SelectListItem{Value="Gray", Text = "Szary"},
                new SelectListItem{Value="Yellow", Text = "Żółty"}
            };
            ViewData["FontColorList"] = liColors;
            ViewData["LineColorList"] = new List<SelectListItem>(liColors);
            ViewData["LayoutList"] = GetLayoutSelectList();
            ViewData["ArrayLayoutList"] = GetArrayLayoutSelectList();
            ViewData["SizeList"] = GetSizeSelectList();
        }
        /// <summary>
        /// Creates structure layouts for dropdown
        /// </summary>
        /// <returns>List of structure layouts</returns>
        private static List<SelectListItem> GetLayoutSelectList()
        {
            Array values = Enum.GetValues(typeof(Layout));
            List<SelectListItem> items = new List<SelectListItem>(values.Length);
            foreach (var i in values)
            {
                items.Add(new SelectListItem
                {
                    Value = Enum.GetName(typeof(Layout), i),
                    Text = Enum.GetName(typeof(PolishLayout), i)
                });
            }
            return items;
        }
        /// <summary>
        /// Creates array layouts for dropdown
        /// </summary>
        /// <returns>List of array layouts</returns>
        private static List<SelectListItem> GetArrayLayoutSelectList()
        {
            Array values = Enum.GetValues(typeof(Layout));
            List<SelectListItem> items = new List<SelectListItem>(values.Length);
            foreach (var i in values)
            {
                items.Add(new SelectListItem
                {
                    Value = Enum.GetName(typeof(Layout), i),
                    Text = Enum.GetName(typeof(PolishArrayLayout), i)
                });
            }
            return items;
        }
        /// <summary>
        /// Creates structure sizes for dropdown
        /// </summary>
        /// <returns>List of structure sizes</returns>
        private static List<SelectListItem> GetSizeSelectList()
        {
            Array values = Enum.GetValues(typeof(StructureSize));
            List<SelectListItem> items = new List<SelectListItem>(values.Length);
            foreach (var i in values)
            {
                items.Add(new SelectListItem
                {
                    Value = Enum.GetName(typeof(StructureSize), i),
                    Text = Enum.GetName(typeof(PolishSize), i)
                });
            }
            return items;
        }
    }
    #endregion
}

GUI/Controllers/StructurePainterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GUI.Controllers
{
    public class StructurePainterController : Controller
    {
        /// <summary>
        /// Main site
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// Examples site
        /// </summary>
        /// <returns></returns>
        public ActionResult Examples()
        {
            return View();
        }
        /// <summary>
        /// Generates site with Instruction file
        /// </summary>
        /// <param name="fileName"></param>
        /// <returns></returns>
        public FilePathResult Download(string fileName)
        {
            return new FilePathResult(string.Format(@"~\App_Data\{0}", fileName + ".pdf"), "application/pdf");
        }
    }
}

GUI/Views/StructurePainter/Examples.cshtml
@{
    ViewBag.Title = "Definicja języka";
}

<img src="../../Images/baner.png" class="img-responsive" />
@*<div class="jumbotron">
        <img src="../../Images/baner.png" style="width: 100%;"/>
        <h1 style="color: #77a809">Structure Painter</h1>
        <p class="lead">Oprogramowanie do wizualizacji struktury danych</p>
    </div>*@
<div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingIntro">
        <h4 class="panel-title">
            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseIntro" aria-expanded="true" aria-controls="collapseIntro">
                Wstęp
            </a>
        </h4>
    </div>
    <div id="collapseIntro" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingIntro">
        <div class="panel-body">
            Structure Painter to pakiet oprogramowania służący do wizualizacji struktur danych na podstawie ich opisu podanego w specjalnie przygotowanym w tym
            celu języku oraz wybranego stylu. Poniżej znajduje się opis języka wraz z przykładami umożliwiający szybkie zapoznanie się z jego możliwościami oraz skorzystanie z aplikacji.
            <div class="margin-top-10">
                Najczęściej popełniane błędy:
                <ul style="padding-left: 20px;">
                    <li>Brak zdefiniowanego obrazka. Należy sprawdzić, czy ustawiona nazwa grafiki zgadza się z nazwą podaną w strukturze.</li>
                    <li>Brak unikalnych nazw dla wgranych obrazków. Każda wgrana grafika powinna mieć inną nazwę. Można ją zmienić w obrazkach</li>
                    <li>
                        Błędnie definiowanie drzew. Dla drzew przy podawaniu krawędzi należy najpierw podać wierzchołek znajdujący się bliżej korzenia (kolejność zstępująca).
                        To znaczy, że jeśli rodzicem wierzchołka <em>4</em> ma być wierzchołek <em>2</em>, to poprawny opis krawędzi będzie: <em>2-4</em>
                        (a dla krawędzi skierowanej <em>2->4</em>), a niepoprawny opis to: <em>4-2</em>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingZero">
        <h4 class="panel-title">
            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseZero" aria-expanded="true" aria-controls="collapseZero">
                Podstawowe
            </a>
        </h4>
    </div>
    <div id="collapseZero" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingZero">
        <div class="panel-body">
            <strong>{ nazwa } </strong> - nazwa wgranego obrazka, powinna zaczynać się od litery, być jednowyrazowa i nie zawierać żadnego ze znaków specjalnych, w szczególności "-" ani ".";
            obrazek, który przekroczy zdefiniowany w ustawieniach maksymalny rozmiar, zostanie do niego przeskalowany z zachowaniem proporcji
            <br />
            <strong>" "</strong> - niweluje specjalne znaczenie znaków wewnątrz (z wyjątkiem "\"), łączy wyrazy w jeden obiekt
            <br />
            <strong>\</strong> - niweluje specjalne znaczenie znaku bezpośrednio po sobie
            <br />
            <strong>spacja (biały znak)</strong> - rozdziela obiekty
            <br /><br />

            Ala ma kota (trzy oddzielne obiekty oddzielone marginesem)
            <br />
            <img src="../../Images/examples/basic1.png" />
            <br /><br />
            "Ala ma kota" (jeden obiekt, wyrazy oddzielone spacją)
            <br />
            <img src="../../Images/examples/basic2.png" />
            <br /><br />
            "< . 1 > \ \ \ " tree{}"
            <br />
            <img src="../../Images/examples/basic3.png" />
            <br /><br />
            \ [ \ | \ ]
            <br />
            <img src="../../Images/examples/basic4.png" />
            <br /><br />
            Ala ma {pies}
            <br />
            <img src="../../Images/examples/basic5.png" />
            <br /><br />
        </div>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
        <h4 class="panel-title">
            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                Tablice
            </a>
        </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
        <div class="panel-body">
            <strong>[ ]</strong> - definicja tablicy
            <br />
            <strong>|</strong> - separator elementów tablicy
            <br /><br />

            [ | | ]
            <br />
            <img src="../../Images/examples/array1.png" />
            <br /><br />
            [ Ala | ma | kota ]
            <br />
            <img src="../../Images/examples/array2.png" />
            <br /><br />
            [ Ala | ma | kota Mruczka [ ale | | nie | | ma psa ] ]
            <br />
            <img src="../../Images/examples/array3.png" />
            <br />
        </div>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
        <h4 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                Tablice haszujące
            </a>
        </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
        <div class="panel-body">
            <strong> obiekt1 > obiekt2</strong> - obiekt2 jest poza tablicą i na niego wskazuje strzałka
            <br />
            <strong>( obiekt1 ) > obiekt2</strong> - obiekt1 jest poza tablicą, strzałka wskazuje na komórkę tablicy zawierającą obiekt2
            <br /><br />


            [ Ala > [ nie | ma | psa ] | ma | kota ]
            <br />
            <img src="../../Images/examples/hasharray1.png" />
            <br /><br />
            [ ( Ala ) > [ nie | ma | psa ] | ma | kota ]
            <br />
            <img src="../../Images/examples/hasharray2.png" />
            <br /><br />
            [ 1 > 2 | ( 3 ) > 4 | ( 5 ) > 6 | 7 > 8 | 9 > 10 ]
            <br />
            <img src="../../Images/examples/hasharray3.png" />
            <br /><br />
        </div>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
        <h4 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                Wektory
            </a>
        </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
        <div class="panel-body">
            Wektory mogą wskazywać na obiekty w jednej tablicy lub na obiekty poza tablicami. Nie można wygenerować wektora o początku w tablicy i końcu poza nią bądź odwrotnie.
            <br />
            <strong> < . nr : label > obiekt</strong> - definicja początku wierzchołka, gdzie nr - numer wektora, label (opcjonalna) - etykieta wektora, obiekt - obiekt będący początkiem wektora
            <br />
            <strong> < nr . > obiekt</strong> - definicja końca wierzchołka, gdzie nr - numer wektora, obiekt - obiekt będący końcem wektora
            <br /><br />

            [ < 2 . > | | < . 2 : dwa > ]
            <br />
            <img src="../../Images/examples/vector1.png" />
            <br /><br />
            [ < 2 . >start | | < . 2 : dwa > koniec wektora]
            <br />
            <img src="../../Images/examples/vector2.png" />
            <br /><br />
            < 2 . >koniec wektora < . 2 : dwa > start
            <br />
            <img src="../../Images/examples/vector3.png" />
            <!--br /><br />
            < 2 . > start < . 2 : dwa > < . 1 > koniec < 1 . > wektora
            <br />
            <img src="../../Images/examples/vector4.png" /-->
            <br /><br />
            < 2 . >a  < . 1 > b < . 2 : dwa> c < 1. > d
            <br />
            <img src="../../Images/examples/vector5.png" />
            <br /><br />
            [ < 2 . > a | | < . 2 : dwa > b ] < . 1 > c < 1 . > d
            <br />
            <img src="../../Images/examples/vector6.png" />
            <br /><br />
        </div>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFour">
        <h4 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                Grafy
            </a>
        </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
        <div class="panel-body">
            Każdy graf i drzewo muszą mieć minimum jeden wierzchołek. Najpierw podawane są definicje wierzchołków, a potem krawędzi. Numery krawędzi i wierzchołków muszą się zgadzać.
            <br />
            Dla drzew przy podawaniu krawędzi należy najpierw podać wierzchołek znajdujący się bliżej korzenia (kolejność zstępująca).
            <br />
            <strong> graph{}</strong> - definicja grafu
            <br />
            <strong> tree{}</strong> - definicja drzewa
            <br />
            <strong> v1:obiekt</strong> - definicja wierzchołka, gdzie: v1 - numer wierzchołka (liczba całkowita), obiekt - zawartość wierzchołka
            <br />
            <strong>=</strong> - separator wierzchołków i krawędzi
            <br />
            <strong>v1->v2:label</strong> - definicja krawędzi skierowanej od wierzchołka o numerze v1 do wierzchołka o numerze v2, label (opcjonalna) - etykieta krawędzi
            <br />
            <strong>v1-v2:label</strong> - definicja krawędzi nieskierowanej między wierzchołkami o numerach v1 i v2, label (opcjonalna) - etykieta krawędzi
            <br />
            <strong>; bądź \n (znak nowej linii)</strong> - separator kolejnych definicji wierzchołków i krawędzi
            <br /><br />

            tree{ 1:1 ; 2:2; 3:3; 4:4; 5:5; 6:6; 7:7; 8:8; =; 1-2; 1-3; 2-4; 2-5; 3-6; 3-7; 4-8;}
            <br />
            <img src="../../Images/examples/graph1.png" />
            <br />
            tree{ 1:Ala ; 2:kota; 3:psa;  =; 1->2:ma; 1->3:nie;}
            <br />
            <img src="../../Images/examples/graf2.png" />
            <br />
            graph{ 1:Warszawa ; 2:Gdańsk; 3:Kraków;  =; 1-2:283 km; 1-3:252 km; 2-3: 485 km;}
            <br />
            <img src="../../Images/examples/graf3.png" />
            <br />
            <br /><br />
        </div>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFive">
        <h4 class="panel-title">
            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="true" aria-controls="collapseFive">
                Zaawansowane
            </a>
        </h4>
    </div>
    <div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFive">
        <div class="panel-body">
            Wszystkie wcześniej omówione struktury można dowolnie zagnieżdżać i łączyć ze sobą
            <br /><br />

            [ < . 1 >{pies}| [[[środek|tablicy]]]| < 1 .> Ali ]
            <br />
            <img src="../../Images/examples/advanced1.png" />
            <br /><br />
            tree{ 1:{Ala} ; 2: kot; 3:[psa];  =; 1->2:ma; 1->3:nie ma;}
            <br />
            <img src="../../Images/examples/advanced2.png" />
            <br /><br />
            "kilka wyrażeń" "każde inne" "jedno pod drugim" (przy wertykalnym układzie)
            <br />
            <img src="../../Images/examples/advanced3.png" />
            <br /><br />
        </div>
    </div>
</div>

GUI/Views/StructurePainter/Index.cshtml
@{
    ViewBag.Title = "O programie";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<img src="../../Images/baner.png" class="img-responsive" />
<div class="jumbotron text-center">
    @*<h1 style="color:#77a809">Structure Painter</h1>*@
    <p class="lead">Oprogramowanie do wizualizacji struktury danych</p>
    <p>
        Używając Structure Painter możesz w sposób szybki i prosty stworzyć wybraną strukturę.
    </p>
    <p>
        Przeczytaj poniżej jak to zrobić bądź ściągnij instrukcję!
    </p>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4><i class="fa fa-fw fa-check"></i> Generator struktur</h4>
            </div>
            <div class="panel-body">
                <p>
                    W programie jest możliwe:
                    <div class="row">
                        <ul>
                            <li>Wgrywanie pliku z gotowym opisem struktury</li>
                            <li>Wgrywanie zdjęć i dodanie ich do struktury</li>
                            <li>Ustawianie własnych styli</li>
                            <li>Zapis struktury w różnych formatach</li>
                        </ul>
                    </div>
                </p>
                <button type="button" class="btn btn-active uppercase" onclick="location.href='@Url.Action("Index", "StructureGenerator")'" formtarget="_blank">Wypróbuj</button>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4><i class="fa fa-fw fa-check"></i> Opis języka</h4>
            </div>
            <div class="panel-body">
                <p>
                    W celu sprawnego zwizualizowania struktur, stworzyliśmy prosty język je opisujący. Dowiedz się więcej, aby móc samemu wygenerować wybraną strukturę
                </p>
                <button type="button" class="btn btn-active uppercase" formtarget="_blank" onclick="location.href='@Url.Action("Examples", "StructurePainter")'">Sprawdź</button>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4><i class="fa fa-fw fa-check"></i>Instrukcja obsługi programu</h4>
            </div>
            <div class="panel-body">
                <p>
                    Użytkownik korzystając z programu ma możliwość wygenerowania struktur danych jako obrazek.
                    W tym celu musi opisać wybrane do wizualizacji dane w specjalnie opracowanym do tego celu języku,
                    którego opis i przykłady użycia znajdzie na stronie w zakładce <em>Przykłady</em>.
                </p>
                <p>
                    W celu generacji struktury należy wpisac definicje struktury do okienka tekstowego, bądź
                    wgrać plik tekstowy poprzez wybranie opcji <em>Wgraj plik</em>. Tekst z pliku zostanie wgrany do
                    okienka tekstowego. W każdym momencie można zmienić opis struktury.
                </p>
               <p style="font-weight:bold">Szczegółową instrukcję można ściągnąć w formie pdf:
                @Html.ActionLink("Instrukcja", "Download", "StructurePainter", new { fileName = "Instrukcja" }, new { @target = "_blank" })
                </p>
            </div>
        </div>
    </div>
</div>